-- Public University

-- NOTE: The public university are listed from the website (https://jpt.mohe.gov.my/index.php/en/hei/public-hei/public-universities)

-- Ranking: https://www.topuniversities.com/world-university-rankings (world university rankings)

-- Universiti Malaya (UM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaya", "Universiti Malaya", "Main Campus", "https://www.um.edu.my/", "Public", "+603-7967 3502/ 3278 / 3279 / 3440 / 3441 / 3448", "skp_aasc@um.edu.my", 58, null, 2026, 251, 300, 2025, 1, 4, 216); -- university id: 1

-- Universiti Sain Malaysia (USM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Sains Malaysia", "Academic Management Division, Registry, Level 2, Chancellory Building, Universiti Sains Malaysia,", "Main Campus", "https://www.usm.my/ms/", "Public", "+604-653 3196", "admissions@usm.my", 134, null, 2026, 401, 500, 2025, 1, 11, 564); -- university id: 2
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email,ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Sains Malaysia", "Kampus Kejuruteraan, Universiti Sains Malaysia", "Engineering Campus", "https://www.eng.usm.my/index.php/ms/", "Public", "+604-599 5999", "pro.eng@usm.my/admissions@usm.my", 134, null, 2026, 401, 500, 2025, 1, 11, 596); -- university id: 3
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Sains Malaysia", "Health Campus, Universiti Sains Malaysia,", "Health Campus", "https://www.kk.usm.my/index.php/en", "Public", "+604-653 3196", "mprckk@usm.my/admissions@usm.my", 134, null, 2026, 401, 500, 2025, 1, 3, 168); -- university id: 4
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Sains Malaysia", "Institut Perubatan & Pergigian Termaju, Universiti Sains Malaysia, Bertam", "IPPT Campus", "https://www.amdi.usm.my/", "Public", "+604-562 2888", "ippt@usm.my/admissions@usm.my", 134, null, 2026, 401, 500, 2025, 1, 11, 579); -- university id: 5

-- Universiti Kebangsaan Malaysia (UKM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Kebangsaan Malaysia", "Universiti Kebangsaan Malaysia", "Main Campus", "https://www.ukm.my/portalukm/", "Public", "+603 8921 5555", "akad@ukm.edu.my", 126, null, 2026, 401, 500, 2025, 1, 15, 756); -- university id: 6

-- Universiti Putra Malaysia (UPM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Putra Malaysia", "Universiti Putra Malaysia", "Main Campus", "https://www.upm.edu.my/", "Public", "+603-9769 1000", "pspk@upm.edu.my", 134, null, 2026, 601, 800, 2025, 1, 15, 744); -- university id: 7
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Putra Malaysia", "Jalan Nyabau", "Bintulu Campus", "https://sarawak.upm.edu.my/", "Public", " +608-685 5888", "upms@upm.edu.my", 134, null, 2026, 601, 800, 2025, 1, 14, 694); -- university id: 8

-- Universiti Teknologi Malaysia (UTM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi Malaysia", "", "Johor Bahru Campus", "https://www.utm.my/", "Public", "+607-553 3333", "corporate@utm.my", 153, null, 2026, 401, 500, 2025, 1, 1, 22); -- university id: 9
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi Malaysia", "Jalan Sultan Yahya Petra", "Kuala Lumpur Campus", "https://kl.utm.my/", "Public", "+603-2615 4100", "oscakl@utm.my",153, null, 2026, 401, 500, 2025, 1, 4, 228); -- university id: 10
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi Malaysia", "Jalan Edu Hub UTM 2, Hub Pendidikan Tinggi Pagoh", "Pagoh Campus", "https://pagoh.utm.my/", "Public", "+606-974 2888", "ica-utmpagoh@utm.my", 153, null, 2026, 401, 500, 2025, 1, 1, 56); -- university id: 11

-- Universiti Islam Antarabangsa Malaysia (UIAM)

INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email,ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Islam Antarabangsa Malaysia", "Jalan Gombak", "Gombak Campus", "https://www.iium.edu.my/v2/", "Public", "(+603) 6421 6421", "webmaster@iium.edu.my", 613, null, 2026, null, null, null, 1, 4, 224); -- university id: 12
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email,ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Islam Antarabangsa Malaysia", "Jalan Sultan Ahmad Shah, Bandar Indera Mahkota,", "Kuantan Campus", "https://www.iium.edu.my/v2/", "Public", "(+609) 570 4000", "webmaster@iium.edu.my", 613, null, 2026, null, null, null, 1, 8, 325); -- university id: 13
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email,ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Islam Antarabangsa Malaysia", "Jalan Sultan Ahmad Shah, Bandar Indera Mahkota", "SASMEC Kuantan", "https://www.iium.edu.my/v2/", "Public", "(+609) 591 2500", "webmaster@iium.edu.my", 613, null, 2026, null, null, null, 1, 8, 325); -- university id: 14
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Islam Antarabangsa Malaysia", "24, Persiaran Tuanku Syed Sirajuddin, Bukit Tunku", "ISTAC Campus", "https://www.iium.edu.my/v2/", "Public", "(+603) 6421 1200", "webmaster@iium.edu.my", 613, null, 2026, null, null, null, 1, 4, 214); -- university id: 15
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Islam Antarabangsa Malaysia", "Universiti Teknologi Malaysia (UTM) Pagoh, Jalan Edu Hub UTM 2, Hub Pendidikan Tinggi", "Pagoh Campus", "https://www.iium.edu.my/v2/", "Public", "(+606) 974 2600", "webmaster@iium.edu.my", 613, null, 2026, null, null, null, 1, 1, 56); -- university id: 16

-- Universiti Utara Malaysia (UUM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email,ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Utara Malaysia", "Sintok,", "Main Campus", "https://www.uum.edu.my/", "Public", "+604-928 4000 / 3053", "servicedesk@uum.edu.my", 491, null, 2026, 401, 500, 2025, 1, 2, 89); -- university id: 17
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email,ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Utara Malaysia", "41-3, Jalan Raja Muda Abdul Aziz,", "KL Campus", "https://uumkl.uum.edu.my/", "Public", "+603-2610 3000 / 2694 9228", "uumkl@uum.edu.my", 491, null, 2026, 401, 500, 2025, 1, 4, 208); -- university id: 18

-- Universiti Malaysia Sarawak (UNIMAS)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Sarawak", "Jln Datuk Mohammad Musa, ", "Main Campus", "https://www.unimas.my/", "Public", "+6082-581165 / 1063/ 1056", "admission_ugrad@unimas.my", 1001, 1200, 2026, 1201, 1500, 2025, 1, 14, 659); -- university id: 19

-- Universiti Malaysia Sabah (UMS) 
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Sabah", "Jalan UMS,", "Main Campus", "https://www.ums.edu.my/v5/", "Public", "+6088 320000 / 320474", "crd@ums.edu.my", 1001, 1200, 2026, 1501, null, 2024, 1, 13, 611); -- university id: 20
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Sabah", "Jalan Sungai Pagar,", "Labuan Campus", "https://www.ums.edu.my/umskal/index.php/ms/", "Public", "+(60)87-503 000", "adminkal@ums.edu.my", 1001, 1200, 2026, 1501, null, 2024, 1, 5, 245); -- university id: 21

-- Universiti Pendidikan Sultan Idris (UPSI)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Pendidikan Sultan Idris", "", "Main Campus", "https://www.upsi.edu.my/?lang=ms", "Public", "+6015-4879 7872/7982/7975", "akademik@upsi.edu.my", 851, 900, 2026, 601, 800, 2025, 1, 9, 513); -- university id: 22

-- Universiti Sains Islam Malaysia (USIM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Sains Islam Malaysia", "Bandar Baru Nilai", "Main Campus", "https://www.usim.edu.my/", "Public", "+606-798 8027", "study@usim.edu.my", 1401, null, 2025, null, null, null, 1, 7, 297); -- university id: 23

-- Universiti Teknologi MARA (UiTM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Kampus Puncak Alam,", "Selangor Branch", "https://selangor.uitm.edu.my/index.php/ms/", "Public", "+603-3258 4000", "korporatucs@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 15, 730); -- university id: 24
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Jalan Meranek", "Sarawak Branch", "https://sarawak.uitm.edu.my/", "Public", "+6082-677 200 | +6082-677 500", "korporat_swk@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 14, 659); -- university id: 25
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "UiTM Cawangan Sabah, Kampus,", "Sabah Branch", "https://sabah.uitm.edu.my/", "Public", "+6088 - 325151", "korporatsabah@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 13, 864); -- university id: 26
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Jalan Purnama, Bandar Seri Alam,", " Pasir Gudang Branch", "https://johor.uitm.edu.my/", "Public", "07-381 8000", "korporatjohor@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 1, 31); -- university id: 27
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Jalan Universiti Off, KM 12, Jalan Muar, Kemajuan Tanah Jementah Batu Sebelas", "Segamat Branch", "https://johor.uitm.edu.my/", "Public", "07-935 2000", "korporatjohor@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 1, 60); -- university id: 28
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "", "Kedah Branch", "https://kedah.uitm.edu.my/", "Public", "+604-456 2000", "korporatkdh@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 2, 125); -- university id: 29
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "UiTM Kelantan, Kampung Belukar", "Kelantan Branch", "https://kelantan.uitm.edu.my/index.php/en/", "Public", "+609-976 2000/3000", "korporatkln@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 3, 201); -- university id: 30
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Universiti Teknologi MARA (UiTM) Cawangan Melaka Kampus, KM 26, Jalan, Lendu,", "Alor Gajah Branch", "https://melaka.uitm.edu.my/index.php/ms/", "Public", " (+606) 558 2000", "korporatmelaka@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 6, 268); -- university id: 31
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "110 Off, Jalan Hang Tuah,", "Bandaraya Melaka Branch", "https://melaka.uitm.edu.my/index.php/ms/", "Public", "(+606) 285 7000", "korporatmelaka@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 6, 253); -- university id: 32
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Universiti Teknologi MARA, Jln Uitm, Kampung Seri Mendapat,", "Jasin Melaka Branch", "https://melaka.uitm.edu.my/index.php/ms/", "Public", " (+606) 264 5000", "korporatmelaka@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 6, 265); -- university id: 33
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "", "Terengganu Branch", "https://terengganu.uitm.edu.my/index.php/en/", "Public", "+609 8400 400", "", 542, null, 2026, 1501, null, 2025, 1, 16, 871); -- university id: 34
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Lintasan Semarak, Bandar Jengka,", "Jengka Branch", "https://pahang.uitm.edu.my/index.php/en/", "Public", "09-460 2000", "korporatjengka@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 8, 344); -- university id: 35
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Universiti Teknologi Mara, UiTM), Cawangan Pahang Kampus, Felda Krau,", "Raub Branch", "https://pahang.uitm.edu.my/index.php/en/", "Public", "09-351 5555", "korporatraub@uitm.edu.mt", 542, null, 2026, 1501, null, 2025, 1, 8, 382); -- university id: 36
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "UiTM Cawangan, Kampung Tok Ebot,", "Pulau Pinang Branch", "https://penang.uitm.edu.my/index.php/en", "Public", "+6(04)382 2888/3598", "korporatpenang@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 11, 585); -- university id: 37
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Universiti Teknologi MARA Perak Branch", "Seri Iskandar Branch", "https://perak.uitm.edu.my/index.php/en/", "Public", "+605-374 2000", "korporatperak@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 9, 459); -- university id: 38
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Tapah Road", "Tapah Branch", "https://perak.uitm.edu.my/index.php/en/", "Public", "+605-406 7000", "korporatperak@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 9, 507); -- university id: 39
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "UiTM Arau,", "Perlis Branch", "https://perlis.uitm.edu.my/", "Public", "+604-9882000", "korporatperlis@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 10, 537); -- university id: 40
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknologi MARA", "Kampung Beting", "Negeri Sembilan Branch", "https://nsembilan.uitm.edu.my/", "Public", "+606-4832100", "korporat@uitm.edu.my", 542, null, 2026, 1501, null, 2025, 1, 7, 301); -- university id: 41

-- Universiti Malaysia Terengganu (UMT)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Terengganu", "Unnamed Road", "Terengganu", "https://www.umt.edu.my/", "Public", "+609-668 4100", "pro@umt.edu.my", 801, 850, 2026, 1001, 1200, 2025, 1, 16, 844); -- university id: 42

-- Universiti Tun Hussein Onn Malaysia (UTHM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Tun Hussein Onn Malaysia", "Persiaran Tun Dr. Ismail,", "Main Campus", "https://uthm.edu.my/en/", "Public", "+607 4537000", "pro@uthm.edu.my", 1001, 1200, 2026, 1201, 1500, 2025, 1, 1, 71); -- university id: 43
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Tun Hussein Onn Malaysia", "KM1, Jln Panchor", "Pagoh Campus", "https://pagoh.uthm.edu.my/", "Public", "+06-9742117/2119", "pro@uthm.edu.my", 1001, 1200, 2026, , , , 1, 1, 56); -- university id: 44

-- Universiti Teknikal Malaysia Melaka (UTeM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Teknikal Malaysia Melaka", "Jalan Hang Tuah Jaya,", "Main Campus", "https://www.utem.edu.my/ms/", "Public", "+606 270 1000", "canselori@utem.edu.my", 1201, 1400, 2026, 1501, null, 2025, 1, 6, 257); -- university id: 45

-- Universiti Malaysia Pahang Al-Sultan Abdullah (UMPSA)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Pahang Al-Sultan Abdullah", "Universiti Malaysia,", "Main Campus", "https://umpsa.edu.my/en", "Public", "+609 431 5000", "pro@umpsa.edu.my", 609, null, 2026, 601, 800, 2025, 1, 8, 351); -- university id: 46
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Pahang Al-Sultan Abdullah", "Universiti Malaysia Pahang Al Sultan Abdullah, Lbh Persiaran Tun Khalil Yaakob, Kampung Melayu Gambang,", "Gambang Campus", "https://umpsa.edu.my/en", "Public", "+609 431 5000", "pro@umpsa.edu.my", 609, null, 2026, , , , 1, 8, 336); -- university id: 47

-- Universiti Malaysia Perlis (UniMAP)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Perlis", "Exit Lebuhraya Changlun - Kuala Perlis,", "Main Campus", "https://www.unimap.edu.my/index.php/ms/", "Public", "+604-9414 224", "webmaster@unimap.edu.my", 1001, 1200, 2026, 1501, null, 2025, 1, 10, 537); -- university id: 48

-- Universiti Sultan Zainal Abidin (UniSZA)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Sultan Zainal Abidin", "Universiti Sultan Zainal Abidin, Kampung Gong Badak,", "Main Campus", "https://www.unisza.edu.my/ms/", "Public", "+609-668 8888", "pro@unisza.edu.my", 1401, null, 2026, 1001, 1200, 2025, 1, 16, 844); -- university id: 49

-- Universiti Malaysia Kelantan (UMK)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Kelantan", "", "Main Campus", "https://www.umk.edu.my/ms/", "Public", " 09-7797000", "pkk@umk.edu.my", 1201, 1400, 2026, 1501, null, 2025, 1, 3, 173); -- university id: 50
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Kelantan", "Karung Berkunci 36, Pengkalan Chepa,", "Kota Campus", "https://www.umk.edu.my/ms/", "Public", "09-771 7000", "pkk@umk.edu.my", 1201, 1400, 2026, 1501, null, 2025, 1, 3, 167); -- university id: 51
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Malaysia Kelantan", "UNIVERSITI MALAYSIA KELANTAN Kampus,", "Jeli Campus", "https://www.umk.edu.my/ms/", "Public", "09-947 7000/7200", "pkk@umk.edu.my", 1201, 1400, 2026, 1501, null, 2025, 1, 3, 193); -- university id: 52


-- Universiti Pertahanan Nasional Malaysia (UPNM)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Pertahanan Nasional Malaysia", "Kem, Sungai Besi,", "Main Campus", "https://www.upnm.edu.my/index.php?req=33", "Public", "603-9051 3400", "", null, null, null, null, null, null, 1, 4, 236); -- university id: 53

-- Private University

-- NOTE: The list of the private university in Malaysia are based on the website (https://www.adscientificindex.com/university-ranking/?country_code=my&funding=Private)

-- Just take the 20 private universities from the website (2025 version)

-- University Teknologi Petronas
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("University Teknologi Petronas", "Persiaran UTP,", "Main Campus", "https://www.utp.edu.my/Pages/Home.aspx", "Private", "1-300-22-8887", "", 251, null, 2026, 201, 250, 2025, 1, 9, 459); -- university id: 54

-- Universiti Tunku Abdul Rahman (UTAR)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Tunku Abdul Rahman", "Jalan Universiti, Bandar Barat,", "Kampar Campus", "https://www.utar.edu.my/", "Private", "605 468 8888", "info@utar.edu.my", 791, 800, 2026, 1001, 1200, 2025, 1, 9, 448); -- university id: 55
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Tunku Abdul Rahman", "Jalan Sungai Long, Bandar Sungai Long,", "Sungai Long Campus", "https://www.utar.edu.my/", "Private", "603 9086 0288", "info@utar.edu.my", 791, 800, 2026, 1001, 1200, 2025, 1, 15, 740); -- university id: 56

-- University of Nottingham Malaysia
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("University of Nottingham Malaysia", "Jln Broga,", "Main Campus", "https://www.nottingham.edu.my/index.aspx", "Private", "+60 3 8924 8686", "study@nottingham.edu.my", 97, null, 2026, 136, null, 2025, 1, 15, 745); -- university id: 57

-- Universiti Tenaga Nasional
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Tenaga Nasional", "Universiti Tenaga Nasional (UNITEN), Putrajaya Campus, Jalan Kajang - Puchong,", "Putrajaya Campus", "https://www.uniten.edu.my/", "Private", "+604-8921 2020", "localadmission@uniten.edu.my", 551, null, 2026, 601, 800, 2025, 1, 15, 740); -- university id: 58
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Universiti Tenaga Nasional", "Jalan Muadzam, Bukit Ibam,", "Sultan Haji Ahmad Shah Campus", "https://www.uniten.edu.my/", "Private", "+609-455 2020", "localadmission@uniten.edu.my", 551, null, 2026, 601, 800, 2025, 1, 8, 362); -- university id: 59

-- Sunway University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Sunway University", "5, Jalan Universiti, Bandar Sunway,", "Main Campus", "https://sunwayuniversity.edu.my/", "Private", "+6(03) 7491 8622", "info@sunway.edu.my", 410, null, 2026, 401, 500, 2025, 1, 15, 806); -- university id: 60

-- UCSI University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("UCSI University", "UCSI Heights, Jln UCSI, Taman Connaught,", "Kuala Lumpur Campus", "https://www.ucsiuniversity.edu.my/kuala-lumpur-campus", "Private", "(+603) 9101 8880", "info.enq@ucsiuniversity.edu.my", 269, null, 2026, null, null, null, 1,4, 234); -- university id: 61
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("UCSI University", "MTLD, Lot 2976, Block 7, Jalan Keruing,", "Kuching Campus", "https://www.ucsiuniversity.edu.my/kuching-campus", "Private", "+6082-596 965", "askswk@ucsiuniversity.edu.my", 269, null, 2026, null, null, null, 1, 14, 648); -- university id: 62

-- Taylor's University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Taylor's University", "1, Jln Taylors,", "LakeSide Campus", "https://university.taylors.edu.my/en.html", "Private", "+603-5629 5000", "", 253, null, 2026, null, null, null, 1, 15, 806); -- university id: 63

-- Multimedia University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Multimedia University", "Persiaran Multimedia,", "Cyberjaya Campus", "https://www.mmu.edu.my/", "Private", "+603-8312 5134 / 5187", "connect@mmu.edu.my", 851, 900, 2026, 1001, 1200, 2025, 1, 15, 821); -- university id: 64
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Multimedia University", "Jalan Ayer Keroh Lama,", "Melaka Campus", "https://www.mmu.edu.my/", "Private", "+606-252 3253 / 3254", "connect@mmu.edu.my", 851, 900, 2026, 1001, 1200, 2025, 1, 6, 255); -- university id: 65

-- Xiamen University Malaysia Campus
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Xiamen University Malaysia Campus", "Jalan Sunsuria, Bandar Sunsuria,", "Malaysia Campus", "https://www.xmu.edu.my/", "Private", "+603 7610 2079", "enquiry@xmu.edu.my", 341, null, 2026, 301, 350, 2025, 1, 15, 760); -- university id: 66

-- AIMST University 
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("AIMST University", "Batu 3 1/2, Jalan, Bukit Air Nasi,", "Main Campus", "https://aimst.edu.my/", "Private", "+604-429 8000", "choose@aimst.edu.my", null, null, null, null, null, null, 1, 2, 117); -- university id: 67

-- University Kuala Lumpur
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("University Kuala Lumpur", "1016, Jln Sultan Ismail, Bandar Wawasan,", "Main Campus", "https://www.unikl.edu.my/", "Private", "+6017-553 9515", "marketing@unikl.edu.my", 1201, 1400, 2026, 1501, null, 2025, 1, 4, 207); -- university id: 68

-- MAHSA University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("MAHSA University", "Jln Sp 2, Bandar Saujana Putra,", "Main Campus", "https://mahsa.edu.my/index.php", "Private", "+603 5102 2200", "marketing@mahsa.edu.my", null, null, null, null, null, null, 1, 15, 734); -- university id: 69

-- Lincoln University College
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Lincoln University College", "No.12, 14, Kolej Universiti Lincoln, 16 & 18, Jalan SS 6/12, Ss 6,", "Petaling Jaya Campus", "https://www.lincoln.edu.my/", "Private", "+603-7806 3478", "info@lincoln.edu.my", 638, null, 2026, null, null, 2025, 1, 15, 802); -- university id: 70

-- Swinburne University of Technology (Sarawak Campus)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Swinburne University of Technology", "Q5B,", "Sarawak Campus", "https://www.swinburne.edu.my/", "Private", "+6082 415 353", "study@swinburne.edu.my", 294, null, 2026, 251, 300, 2025, 1, 14, 654); -- university id: 71

-- Management and Science University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Management and Science University", "University Drive, Off Persiaran Olahraga,", "Main Campus", "https://www.msu.edu.my/", "Private", "+(603) 5521 6868", "", 597, null, 2026, 801, 1000, 2025, 1, 15, 709); -- university id: 72

-- SeGi University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("SeGi University", "9, Jalan Teknologi, Pju 5 Kota Damansara,", "main Campus", "https://www.segi.edu.my/", "Private", "603 6145 1777", "infokd@segi.edu.my", 731, 740, 2026, null, null, 2025, 1, 15, 814); -- university id: 73

-- Asia Pacific University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Asia Pacific University", "jalan Teknologi 5, Taman Teknologi Malaysia,", "Main Campus", "https://www.apu.edu.my/", "Private", "+603 8996 1000", "info@apu.edu.my", 597, null, 2026, null, null, null, 1, 4, 236); -- university id: 74

-- Heriot-Watt University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Heriot-Watt University", "1, Jalan Venna P5/2, Precinct 5,", "Malaysia Campus", "https://www.hw.ac.uk/malaysia", "Private", "+603 8894 3888", "hwum@hw.ac.uk", 287, null, 2026, 401, 500, 2025, 1, 12, 865); -- university id: 75

-- INTI International University
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("INTI International University", "Persiaran Perdana BBN Putra Nilai,", "Main Campus", "https://newinti.edu.my/", "Private", "(+606) 798 2000", "enquiry.international@newinti.edu.my", 509, null, 2026, null, null, null, 1, 7, 297); -- university id: 76

-- Tunku Abdul Rahman University Management and Technology (TARUMT)
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Tunku Abdul Rahman University Management and Technology", "Ground Floor, Bangunan Tan Sri Khow Kai Boh (Block A), Jalan Genting Kelang, Setapak,", "Kuala Lumpur Campus", "https://tarc.edu.my/", "Private", "(6)03-41450123", "info@tarc.edu.my", null, null, null, null, null, null, 1, 4, 226); -- university id: 77
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Tunku Abdul Rahman University Management and Technology", "77, Lorong Lembah Permai 3,", "Penang Campus", "https://penang.tarc.edu.my/", "Private", "(6)04-8995230", "penang@tarc.edu.my", null, null, null, null, null, null, 1, 11, 558); -- university id: 78
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Tunku Abdul Rahman University Management and Technology", "Jln Kolej, Taman Bandar Baru,", "Perak Campus", "https://perak.tarc.edu.my/", "Private", "(6)05-4660388, 4668012/3", "perak@tarc.edu.my", null, null, null, null, null, null, 1, 9, 448); -- university id: 79
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Tunku Abdul Rahman University Management and Technology", "Jln Kolej TAR,", "Johor Campus", "https://johor.tarc.edu.my/", "Private", "(6)07-9270801/3", "johor@tarc.edu.my", null, null, null, null, null, null, 1, 1, 60); -- university id: 80
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Tunku Abdul Rahman University Management and Technology", "Jalan IM 9/2, Bandar Indera Mahkota,", "Pahang Campus", "https://pahang.tarc.edu.my/", "Private", "(6)09-573 8171", "pahang@tarc.edu.my", null, null, null, null, null, null, 1, 8, 325); -- university id: 81
INSERT INTO universities (uni_name, uni_address, campus, website, uni_type, contact_no, email, ranking_qs_no_start, ranking_qs_no_end, ranking_qs_year, ranking_the_no_start, ranking_the_no_end, ranking_the_year, admin_id, state_id, area_id) VALUES ("Tunku Abdul Rahman University Management and Technology", "No.1, Jalan Alamesra,", "Sabah Campus", "https://sabah.tarc.edu.my/", "Private", "(6)088-348080 / (6)011-10825619", "sabah@tarc.edu.my", null, null, null, null, null, null, 1, 13, 612); -- university id: 82